#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

help() {
    echo "Invalid command: choose one of 'upd'"
}

if [ "$#" -lt 1 ]; then
    help
    exit 1
fi

if [ "$1" = upd ]; then

    echo "About to update the box, pausing 5s"
    sleep 5
    cd $(mktemp -d)
    wget https://aidanhs.com/local.tar.gz
    rm -rf ~/local
    tar -C ~ -xf local.tar.gz
    rm local.tar.gz
    boxtool _postupdate

elif [ "$1" = _postupdate ]; then

    # INTERNAL FUNCTION - DO NOT CALL

    echo
    echo "> CLEANUP"

    if [ -e ~/.config/autostart/dropbox.desktop -o -e ~/.dropbox -o -e ~/Dropbox ]; then
        rm -f ~/.config/autostart/dropbox.desktop
        echo "Please run the following to clean up dropbox"
        echo "rm -r ~/.dropbox*"
        echo "rm -r ~/Dropbox"
        sleep 15
    fi

    echo
    echo "> INSTALL/REPLACE"

    echo "Setting up syncthing for desktop machines"
    mkdir -p ~/.config/autostart
    cp ~/local/etc/syncthing-start.desktop ~/.config/autostart/
    echo "If this is the first time setting up syncthing, log out and in, and run 'syncthing -browser-only'"

    echo "Setting up homeshick"
    if [ ! -d ~/.homesick ]; then
        git clone https://github.com/andsens/homeshick.git ~/.homesick/repos/homeshick
        # --batch will *not* auto symlink
        ~/.homesick/repos/homeshick/bin/homeshick --batch clone git@bitbucket.org:aidanhs/dotfiles.git
        ~/.homesick/repos/homeshick/bin/homeshick link
        chmod 600 ~/.homesick/repos/dotfiles/home/.ssh/config
    fi
    ~/.homesick/repos/homeshick/bin/homeshick pull
    ~/.homesick/repos/homeshick/bin/homeshick symlink

    echo "Setting up tmux"
    # Note: bash -i picks up bashrc from above so we can get tmux
    if [ ! -d ~/.tmux/plugins/tpm ]; then
        git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
        bash -i ~/.tmux/plugins/tpm/bin/install_plugins
    fi
    bash -i ~/.tmux/plugins/tpm/bin/update_plugins all

    echo "Setting up nvim"
    ~/local/bin/nvim --headless -c ':PlugInstall' -c ':qa'

    echo "Make sure to log in and log out to pick up any bashrc changes!"

else

    help
    exit 1

fi
